AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  TargetRubyVersion: 3.0
  Exclude:
    - 'test/**/test_*.rb'

Metrics/MethodLength:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
Style/Copyright:
  Enabled: false
